name: BetterRepair
main: GamerMJay\BetterRepair\Main
author: GamerMJay
api: 5.0.0
description: Easy Repair plugin
version: 1.1.0
website: https://github.com/GamerMJay/BetterRepair

permissions:
  repair.use:
    default: op
  repair.all:
    default: op
