name: BetterRepair
main: GamerMJay\BetterRepair\Main
author: GamerMJay
api: 4.0.0
description: Easy Repair plugin
version: 3.0.0
website: https://github.com/GamerMJay/BetterRepair


permissions:
  repair.use:
    default: op
