# BetterRepair V1.1.0 by GamerMJay, licensed under Apache License 2.0
#######

# repair
  repair: "repair"
  repair-description: "Repair your Item in your Hand"
  noPermission: "§6§lBetterRepair §r§8» §You don't have permission."
  repair-noitem: "§6§lBetterRepair §r§8» §cYou have no item in your Hand!"
  instanceof: "§6§lBetterRepair §r§8» §cYou cannot repair this item"
  repair-succes: "§6§lBetterRepair §r§8» §aYou have been repaired."
  
# repairall
  repair-all: "repairall"
  repair-all-description: "Repairs all your items"
  noPermission: "§6§lBetterRepair §r§8» §cYou don't have permission."
  repair-all-message: "§6§lBetterRepair §r§8» §aAll items in your inventory has been repaired!"

# run ingame
  run-ingame: "§6§lBetterRepair §r§8» §crun this command ingame!"
