# BetterRepair V1.0.0 by GamerMJay, licensed under Apache License 2.0!


# Messages
command: "repair"
description: "Repair your Item in your Hand"
command-repair-all: "repairAllCommand"
description-repair-all: "Repairs all your items"
permission-repair-all: "betterrepair.repair.all"
instanceof: "§6§lBetterRepair §r§8» §cYou cannot repair this item"
no-permission: "§6§lBetterRepair §r§8» §cyou have no permission!"
run-ingame: "§6§lBetterRepair §r§8» §crun this command ingame!"
repair-succes: "§6§lBetterRepair §r§8» §aYour item has been repaired"
repair-noitem: "§6§lBetterRepair §r§8» §cYou have no item in your Hand!"
repair-all-success: "§6§lBetterRepair §r§8» §aAll items in your inventory has been repaired!"
